server.port=8085

# SQLite JPA Configuration
spring.datasource.url=jdbc:sqlite:elysium.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=com.elysium.residences.data.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=com.elysium.residences.data.SQLiteDialect

# Dev mode details
vaadin.productionMode=false
logging.level.org.springframework=INFO
logging.level.com.vaadin=INFO
logging.level.com.elysium=DEBUG
